# frontend/Dockerfile
FROM node:18
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Copy index.html and static assets to dist directory
RUN cp index.html dist/
RUN cp -r favicon_io dist/
RUN npm install -g serve
EXPOSE 5173
CMD ["serve", "dist", "-l", "5173"]
